#!/usr/bin/env python3
"""series_status_report.py <S-number> — the one-page Series Status Report (P4b, LOCKED design §2).

A PURE PROJECTION of receipts that already exist: roadmap (book stages) + extrusion
validation state (binding statuses) + adversary records + the code-status store.
Nothing here is hand-typed, so the report cannot drift from the record.
the operator's series-level provisional click-through references this file's sha256
(press harden --approve-report <sha>).

Usage: series_status_report.py 2 [--out DIR]
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import time
from pathlib import Path

import yaml

from . import review_state as _review

REPO = Path(os.environ.get("PRESS_DATA_ROOT") or Path.cwd())
STATE_P = REPO / "memory" / "extrusion_validation_state.json"
ADV_DIR = REPO / "artifacts" / "adversary"
CODE_STATUS_P = Path(os.environ.get("PRESS_HOME") or Path.cwd()) / "code_status.json"


def _slug_tokens(title):
    return {w for w in "".join(c if c.isalnum() else " " for c in title.lower()).split()
            if len(w) > 3}


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: series_status_report.py <series-number> [--out DIR]")
    args = sys.argv[1:]
    out_dir = Path(os.environ.get("PRESS_REPORTS_DIR") or (Path(os.environ.get("PRESS_HOME") or Path.cwd()) / "reports"))
    if "--out" in args:
        i = args.index("--out")
        out_dir = Path(args[i + 1])
        del args[i:i + 2]
    raw = args[0].upper().lstrip("S")
    if not raw.isdigit():
        sys.exit(f"REPORT FAIL: series id must be N or SN — got {args[0]!r}")
    n = int(raw)
    roadmap = yaml.safe_load((REPO / "artifacts" / "series_roadmap.yaml").read_text())
    ser = next((s for s in roadmap["series"] if s.get("series_number") == n), None)
    if ser is None:
        sys.exit(f"REPORT FAIL: no series numbered {n} in the golden record")
    state = json.loads(STATE_P.read_text()) if STATE_P.exists() else {"anchors": []}
    code_status = json.loads(CODE_STATUS_P.read_text()) if CODE_STATUS_P.exists() else {}

    ts = time.strftime("%Y-%m-%d", time.gmtime())
    catalog_hash = hashlib.sha256(
        (REPO / "artifacts" / "series_roadmap.yaml").read_bytes()).hexdigest()[:16]
    rows, proposed, excluded = [], [], []
    for t in ser.get("titles", []) or []:
        title = t.get("title", "?")
        stage = (t.get("stage") or "—")[:26]
        book_id = t.get("book_id") or ""
        anchors = [a for a in state["anchors"]
                   if a.get("book_id") == book_id or
                   (book_id == "" and _slug_tokens(title) & _slug_tokens(a.get("book_id", "").replace("_", " ")))]
        if anchors:
            statuses = {a["status"] for a in anchors}
            extr = "VALIDATED" if statuses == {"VALIDATED"} else "/".join(sorted(statuses))
        else:
            extr = "no bindings"
        adv = "—"
        for d in ADV_DIR.glob("*") if ADV_DIR.exists() else []:
            if d.is_dir() and _slug_tokens(title) & _slug_tokens(d.name.replace("-", " ").replace("_", " ")):
                recs = sorted(d.glob("*.json"))
                if recs:
                    last = json.loads(recs[-1].read_text())
                    adv = f"{last['result']} {last['ts'][:8]}"
        cs = code_status.get(t.get("press_id") or title, {}).get("status", "—")
        review = _review.summary(t.get("press_id") or book_id or title)
        eligible = bool(anchors) and extr == "VALIDATED"
        (proposed if eligible else excluded).append(
            (title, None if eligible else f"extrusion: {extr}"))
        rows.append((title[:46], stage, cs, extr, adv, review))

    L = [f"# SERIES STATUS REPORT — S{n} · {ser.get('name', '')}",
         f"\nEdition stamp: {ts} · catalog `{catalog_hash}` · generated by the Press "
         "(pure projection — no hand-typed line)",
         f"\nSeries status (roadmap, verbatim): {str(ser.get('status'))[:220]}", "",
         "| volume | book stage | code_status | extrusion bindings | adversary | human review (visibility) |",
         "|---|---|---|---|---|---|"]
    L += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |" for r in rows]
    prop_names = [p[0] for p in proposed]
    L += ["", f"**PROPOSED PROVISIONAL SET:** {prop_names or 'NONE — no volume meets the hardening floor'}"]
    if excluded:
        L += ["", "**NOT proposed (reason):**"]
        L += [f"- {t}: {r}" for t, r in excluded]
    L += ["", "**HUMAN REVIEW is VISIBILITY ONLY (R-1):** the column above projects recorded",
          "board/lens/read events — it is not a floor check and blocks nothing. It exists so",
          "the hand that speaks the word can see which human lenses have and have not run.",
          "", "**STILL REQUIRES DETAILED SEAL:** every volume above — provisional ≠ sealed.",
          "", "*Promotion requires the human word (`press harden --approve-report <this file's sha256>`).",
          "Demotion is automatic and fail-closed on any hardening finding (operator ruling026-07-16).*"]
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"SERIES_S{n}_STATUS_{ts}.md"
    body = "\n".join(L) + "\n"
    out.write_text(body, encoding="utf-8")
    sha = hashlib.sha256(body.encode()).hexdigest()
    print(f"[report] {out}  report_sha={sha[:16]}")
    print(f"  proposed provisional: {prop_names or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
